let data=[
	'1-CRP 1100 - The American City-https://classes.cornell.edu/browse/roster/FA18/class/CRP/1100',
	'2-CRP 1101 - The Global City-https://classes.cornell.edu/browse/roster/SP19/class/CRP/1101',
	'3-CRP 1106 - URS First-Year Seminar-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'4-CRP 1109 - FWS: Cities and Regions-https://classes.cornell.edu/browse/roster/SP19/class/CRP/1109',
	'5-CRP 2000 - The Promise and Pitfalls of Contemporary Planning-https://classes.cornell.edu/browse/roster/FA18/class/CRP/2000',
	'6-CRP 2010 - People, Planning, and Politics in the City-https://classes.cornell.edu/browse/roster/SP19/class/CRP/2010',
	'7-CRP 2610 - Fieldwork in Urban Archaeology-https://classes.cornell.edu/browse/roster/FA18/class/CRP/2610',
	'8-CRP 3010 - Public Administration-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'9-CRP 3011 - Ethics, Development, and Globalization-https://classes.cornell.edu/browse/roster/FA17/class/CRP/3011',
	'10-CRP 3071 - City and Regional Workshop-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'11-CRP 3072 - Land Use, Environmental Planning, and Urban Design Workshop-https://classes.cornell.edu/browse/roster/SP19/class/CRP/3072',
	'12-CRP 3090 - Community Development Seminar-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'13-CRP 3101 - Race, Space and Place-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'14-CRP 3103 - Asian American Politics and Public Policy-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'15-CRP 3105 - Urban Political Economy Seminar: Property and Expropriation-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'16-CRP 3106 - Structural Barriers to Equity in Planning I-https://classes.cornell.edu/browse/roster/SP19/class/CRP/3106',
	'17-CRP 3107 - Structural Barriers to Equity in Planning II-https://classes.cornell.edu/browse/roster/SP19/class/CRP/3107',
	'18-CRP 3111 - Immigrant Entrepreneurship US City: The Latin Case-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'19-CRP 3180 - Politics of Community Development-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'20-CRP 3201 - Qualitative Research and Design Methods-https://classes.cornell.edu/browse/roster/FA17/class/CRP/3201',
	'21-CRP 3202 - Visual Methods in Planning-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'22-CRP 3210 - Introduction to Quantitative Methods for the Analysis of Public Policy-https://classes.cornell.edu/browse/roster/FA18/class/CRP/3210',
	'23-CRP 3270 - Regional Economic Impact Analysis-https://classes.cornell.edu/browse/roster/FA18/class/CRP/3270',
	'24-CRP 3280 - Overview: Quantitative Methods in Policy Analysis-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'25-CRP 3301 - Urban Mentorship Initiative-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'26-CRP 3310 - Social Justice and the City: Preparation for Urban Fieldwork-https://classes.cornell.edu/browse/roster/SP15/class/CRP/3310',
	'27-CRP 3320 - Post-Fieldwork Writing Seminr in Urban Policy-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'28-CRP 3348 - Design Connect-https://classes.cornell.edu/browse/roster/SP19/class/CRP/3348',
	'29-CRP 3401 - Urban Redevelopment-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'30-CRP 3430 - Affordable Housing Policy and Programs-https://classes.cornell.edu/browse/roster/FA18/class/CRP/3430',
	'31-CRP 3502 - Suburbia-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'32-CRP 3504 - Comparative Urban Development: The European Case-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'33-CRP 3506 - Environmental Planning Seminar: Wilderness and Wildlands-https://classes.cornell.edu/browse/roster/FA14/class/CRP/3506',
	'34-CRP 3540 - Introduction to Environment Planning-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'35-CRP 3600 - Pre-Industrial Cities and Towns in North America-https://classes.cornell.edu/browse/roster/SP18/class/CRP/3600',
	'36-CRP 3601 - Museum and the Public-https://classes.cornell.edu/browse/roster/SP18/class/CRP/3601',
	'37-CRP 3602 - Planning History: The American Case-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'38-CRP 3610 - Seminar in American Urban History-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'39-CRP 3650 - Gender and Globalization-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'40-CRP 3720 - Contemporary Italy: Politics and Society-https://classes.cornell.edu/browse/roster/SP19/class/CRP/3720',
	'41-CRP 3721 - Italy and the European Union-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'42-CRP 3723 - European Cities-https://classes.cornell.edu/browse/roster/SP18/class/CRP/3723',
	'43-CRP 3750 - Nilgiris Field Learning Center (NFLC) Preparatory Seminar-https://classes.cornell.edu/browse/roster/FA18/class/CRP/3750',
	'44-CRP 3760 - Latino/a Latin American Cities-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'45-CRP 3801 - Asian American Urban Experience-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'46-CRP 3810 - Principles of Spatial Design and Aesthetics-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'47-CRP 3820 - Introduction to Physical Planning-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'48-CRP 3840 - Green Cities-https://classes.cornell.edu/browse/roster/FA18/class/CRP/3840',
	'49-CRP 3850 - Special Topics in Planning-https://classes.cornell.edu/browse/roster/SP19/class/CRP/3850',
	'50-CRP 3851 - Special Topics in Design-https://classes.cornell.edu/browse/roster/FA14/class/CRP/3851',
	'51-CRP 3852 - Special Topics in Urban History, Society, and Politics-https://classes.cornell.edu/browse/roster/SP16/class/CRP/3852',
	'52-CRP 3854 - Special Topics in Regional Development and Globalization-https://classes.cornell.edu/browse/roster/FA18/class/CRP/3854',
	'53-CRP 3855 - Special Topics in Planning Methods-https://classes.cornell.edu/browse/roster/FA17/class/CRP/3855',
	'54-CRP 3860 - Planning for Sustainable Transportation-https://classes.cornell.edu/browse/roster/SP19/class/CRP/3860',
	'55-CRP 3899 - Special Topics in Planning: West Campus (LWYL)-https://classes.cornell.edu/browse/roster/SP19/class/CRP/3899',
	'56-CRP 3900 - City and Regional Futures: Planning Practice, Policy and Design-https://classes.cornell.edu/browse/roster/SP19/class/CRP/3900',
	'57-CRP 3901 - Seminar on International Planning-https://classes.cornell.edu/browse/roster/FA14/class/CRP/3901',
	'58-CRP 3902 - Race, Migration and the American City-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'59-CRP 4040 - Urban Economics-https://classes.cornell.edu/browse/roster/SP19/class/CRP/4040',
	'60-CRP 4080 - Introduction to Geographic Information Systems (GIS)-https://classes.cornell.edu/browse/roster/FA18/class/CRP/4080',
	'61-CRP 4120 - Devolution and Privatization: Challenges for Urban Public Management-https://classes.cornell.edu/browse/roster/FA18/class/CRP/4120',
	'62-CRP 4160 - Rome Workshop-https://classes.cornell.edu/browse/roster/SP19/class/CRP/4160',
	'63-CRP 4170 - Economic Development: Firms, Industries, and Regions-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'64-CRP 4440 - Resource Management and Environment Law-https://classes.cornell.edu/browse/roster/SP19/class/CRP/4440',
	'65-CRP 4570 - Community Development Seminar-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'66-CRP 4590 - Legal Aspects of Land Use Planning-https://classes.cornell.edu/browse/roster/SP19/class/CRP/4590',
	'67-CRP 4740 - Urban Transformations in the Global South-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'68-CRP 4770 - Seminar on Issues in African Development-https://classes.cornell.edu/browse/roster/SP19/class/CRP/4770',
	'69-CRP 4900 - Student-Faculty Research-https://classes.cornell.edu/browse/roster/SP19/class/CRP/4900',
	'70-CRP 4904 - Professional Practice Seminar: New York City-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'71-CRP 4920 - Undergraduate Honors Thesis Research-https://classes.cornell.edu/browse/roster/SP19/class/CRP/4920',
	'72-CRP 4930 - Undergraduate Honors Thesis Writing-https://classes.cornell.edu/browse/roster/SP19/class/CRP/4930',
	'73-CRP 4940 - URS Internship-https://classes.cornell.edu/browse/roster/FA18/class/CRP/4940',
	'74-CRP 4970 - Independent Study-https://classes.cornell.edu/browse/roster/SP19/class/CRP/4970',
	'75-CRP 5000 - Modular Course-https://classes.cornell.edu/browse/roster/SP15/class/CRP/5000',
	'76-CRP 5040 - Urban Economics-https://classes.cornell.edu/browse/roster/SP19/class/CRP/5040',
	'77-CRP 5071 - City and Regional Planning Workshop-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'78-CRP 5072 - Land Use, Environmental Planning, and Urban Design Workshop-https://classes.cornell.edu/browse/roster/SP19/class/CRP/5072',
	'79-CRP 5073 - Historic Preservation Planning Workshop-https://classes.cornell.edu/browse/roster/SP17/class/CRP/5073',
	'80-CRP 5074 - Economic and Community Development Workshop-https://classes.cornell.edu/browse/roster/FA18/class/CRP/5074',
	'81-CRP 5075 - Real Estate Project Workshop-https://classes.cornell.edu/browse/roster/SP16/class/CRP/5075',
	'82-CRP 5076 - International Planning and Development Workshop-https://classes.cornell.edu/browse/roster/SP19/class/CRP/5076',
	'83-CRP 5080 - Introduction to GIS for Planners-https://classes.cornell.edu/browse/roster/SP19/class/CRP/5080',
	'84-CRP 5090 - Community Development Seminar-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'85-CRP 5106 - Structural Barriers to Equity in Planning I-https://classes.cornell.edu/browse/roster/SP19/class/CRP/5106',
	'86-CRP 5107 - Structural Barriers to Equity in Planning II-https://classes.cornell.edu/browse/roster/SP19/class/CRP/5107',
	'87-CRP 5120 - Public and Spatial Economics for Planners-https://classes.cornell.edu/browse/roster/FA18/class/CRP/5120',
	'88-CRP 5122 - Intermediate Microeconomics for Public Affairs-https://classes.cornell.edu/browse/roster/FA17/class/CRP/5122',
	'89-CRP 5130 - Introduction to Planning Practice and History-https://classes.cornell.edu/browse/roster/FA18/class/CRP/5130',
	'90-CRP 5170 - Economic Development: Firms, Industries, and Regions-https://classes.cornell.edu/browse/roster/SP16/class/CRP/5170',
	'91-CRP 5172 - NYC Workshop: Land Use, Environmental Planning, and Design-https://classes.cornell.edu/browse/roster/FA18/class/CRP/5172',
	'92-CRP 5173 - NYC Studio: Integrated Urbanism as a Platform for Engagement-https://classes.cornell.edu/browse/roster/FA18/class/CRP/5173',
	'93-CRP 5174 - NYC Colloquium: Professional Practice-https://classes.cornell.edu/browse/roster/FA18/class/CRP/5174',
	'94-CRP 5180 - Politics of Community Development-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'95-CRP 5190 - History and Theory of Urban Spatial Development-https://classes.cornell.edu/browse/roster/SP19/class/CRP/5190',
	'96-CRP 5230 - Analytical Mapping and Spatial Modeling-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'97-CRP 5250 - Introductory Methods of Planning Analysis-https://classes.cornell.edu/browse/roster/SP19/class/CRP/5250',
	'98-CRP 5280 - Overview: Quantitative Methods in Policy Analysis-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'99-CRP 5320 - Real Estate Development Process I-https://classes.cornell.edu/browse/roster/FA18/class/CRP/5320',
	'100-CRP 5321 - Real Estate Development Process II-https://classes.cornell.edu/browse/roster/FA18/class/CRP/5321',
	'101-CRP 5330 - Real Estate Marketing and Management-https://classes.cornell.edu/browse/roster/FA14/class/CRP/5330',
	'102-CRP 5348 - Design Connect-https://classes.cornell.edu/browse/roster/SP19/class/CRP/5348',
	'103-CRP 5370 - Real Estate Seminar Series-https://classes.cornell.edu/browse/roster/SP19/class/CRP/5370',
	'104-CRP 5440 - Resource Management and Environmental Law-https://classes.cornell.edu/browse/roster/SP19/class/CRP/5440',
	'105-CRP 5450 - Inferential Statistics for Planning and Public Policy-https://classes.cornell.edu/browse/roster/SP19/class/CRP/5450',
	'106-CRP 5460 - Introduction to Community and Environment Dispute Resolution-https://classes.cornell.edu/browse/roster/SP19/class/CRP/5460',
	'107-CRP 5520 - Land Use Planning-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'108-CRP 5530 - Land Use Planning Methods-https://classes.cornell.edu/browse/roster/SP19/class/CRP/5530',
	'109-CRP 5540 - Introduction to Environmental Planning-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'110-CRP 5560 - Creating the Built Environment-https://classes.cornell.edu/browse/roster/FA18/class/CRP/5560',
	'111-CRP 5561 - Innovation and Strategy in Commercial Real Estate Development-https://classes.cornell.edu/browse/roster/FA18/class/CRP/5561',
	'112-CRP 5562 - Zoning, Entitlements and Subdivision Regulations-https://classes.cornell.edu/browse/roster/SP19/class/CRP/5562',
	'113-CRP 5563 - Real Estate Project Workshop-https://classes.cornell.edu/browse/roster/SP19/class/CRP/5563',
	'114-CRP 5565 - Urban Economics and Real Estate Markets-https://classes.cornell.edu/browse/roster/FA18/class/CRP/5565',
	'115-CRP 5590 - Legal Aspects of Land Use Planning-https://classes.cornell.edu/browse/roster/SP19/class/CRP/5590',
	'116-CRP 5600 - Documentation for Preservation-https://classes.cornell.edu/browse/roster/FA18/class/CRP/5600',
	'117-CRP 5610 - Historic Preservation Planning Workshop: Surveys-https://classes.cornell.edu/browse/roster/FA18/class/CRP/5610',
	'118-CRP 5620 - Perspectives on Preservation-https://classes.cornell.edu/browse/roster/FA18/class/CRP/5620',
	'119-CRP 5630 - Problems in Contemporary Preservation Practice-https://classes.cornell.edu/browse/roster/SP18/class/CRP/5630',
	'120-CRP 5640 - Building Materials Conservation-https://classes.cornell.edu/browse/roster/SP19/class/CRP/5640',
	'121-CRP 5650 - Fieldwork or Workshop in History and Preservation-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'122-CRP 5660 - Planning and Preservation Practice: Urban Field Trip-https://classes.cornell.edu/browse/roster/FA18/class/CRP/5660',
	'123-CRP 5661 - Planning and Preservation Practice: Work Weekend-https://classes.cornell.edu/browse/roster/SP19/class/CRP/5661',
	'124-CRP 5662 - Planning and Preservation Practice: Preservation National Conference-https://classes.cornell.edu/browse/roster/FA18/class/CRP/5662',
	'125-CRP 5670 - Measured Drawing-https://classes.cornell.edu/browse/roster/SP18/class/CRP/5670',
	'126-CRP 5810 - Principles of Spatial Design and Aesthetics-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'127-CRP 5820 - Principles of Site Planning and Urban Design-https://classes.cornell.edu/browse/roster/FA18/class/CRP/5820',
	'128-CRP 5840 - Green Cities-https://classes.cornell.edu/browse/roster/FA18/class/CRP/5840',
	'129-CRP 5850 - Special Topics-https://classes.cornell.edu/browse/roster/SP19/class/CRP/5850',
	'130-CRP 5851 - Special Topics in Design-https://classes.cornell.edu/browse/roster/FA18/class/CRP/5851',
	'131-CRP 5852 - Special Topics in Urban History, Society, and Politics-https://classes.cornell.edu/browse/roster/SP16/class/CRP/5852',
	'132-CRP 6010 - Public Administration-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'133-CRP 6011 - Ethics, Development, and Globalization-https://classes.cornell.edu/browse/roster/FA17/class/CRP/6011',
	'134-CRP 6012 - Legal Aspects of Public Agency Decision-Making-https://classes.cornell.edu/browse/roster/FA14/class/CRP/6012',
	'135-CRP 6050 - Urban Public Finance-https://classes.cornell.edu/browse/roster/SP15/class/CRP/6050',
	'136-CRP 6090 - Special Topics in Urban and Regional Theory-https://classes.cornell.edu/browse/roster/FA18/class/CRP/6090',
	'137-CRP 6101 - Race, Space and Place-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'138-CRP 6102 - Economics of Financial Crises-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'139-CRP 6103 - Asian American Politics and Public Policy-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'140-CRP 6105 - Urban Political Economy Seminar: Property and Expropriation-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'141-CRP 6111 - Immigrant Entrepreneurship US City: The Latin Case-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'142-CRP 6120 - Devolution and Privatization: Challenges for Urban Public Management-https://classes.cornell.edu/browse/roster/FA18/class/CRP/6120',
	'143-CRP 6150 - Current Issues and Debates on NGOs-https://classes.cornell.edu/browse/roster/FA17/class/CRP/6150',
	'144-CRP 6190 - Special Topics: Planning Theory & Politics-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'145-CRP 6201 - Qualitative Methods-https://classes.cornell.edu/browse/roster/FA17/class/CRP/6201',
	'146-CRP 6202 - Visual Methods in Planning-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'147-CRP 6210 - SP TP: Quantitative Methods & Analysis-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'148-CRP 6220 - Planning Policy and Analysis-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'149-CRP 6270 - Regional Economic Impact Analysis-https://classes.cornell.edu/browse/roster/FA18/class/CRP/6270',
	'150-CRP 6290 - Advanced Topics in GIS-https://classes.cornell.edu/browse/roster/SP19/class/CRP/6290',
	'151-CRP 6291 - SPTP: Research and Project Design-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'152-CRP 6311 - Consulting for Nonprofit and Government Organizations-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'153-CRP 6330 - Methods of Regional Science and Planning II-https://classes.cornell.edu/browse/roster/SP19/class/CRP/6330',
	'154-CRP 6390 - Special Topics in Regional Development Planning-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'155-CRP 6391 - Special Topics: Comparative Public Administration: The Case of Seoul, Korea-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'156-CRP 6401 - Urban Redevelopment-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'157-CRP 6430 - Affordable Housing Policy and Programs-https://classes.cornell.edu/browse/roster/FA18/class/CRP/6430',
	'158-CRP 6490 - Special Topics: Social-Policy Planning-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'159-CRP 6502 - Suburbia-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'160-CRP 6504 - Comparative Urban Development: The European Case-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'161-CRP 6506 - Environmental Planning Seminar: Wilderness and Wildlands-https://classes.cornell.edu/browse/roster/FA14/class/CRP/6506',
	'162-CRP 6560 - Real Estate Transactions and Deal Structuring-https://classes.cornell.edu/browse/roster/SP19/class/CRP/6560',
	'163-CRP 6565 - International Cases and Contracts-https://classes.cornell.edu/browse/roster/SP19/class/CRP/6565',
	'164-CRP 6570 - Real Estate Law-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'165-CRP 6580 - Residential and Commercial Development-https://classes.cornell.edu/browse/roster/SP19/class/CRP/6580',
	'166-CRP 6590 - Special Topics: Urban Development Planning-https://classes.cornell.edu/browse/roster/SP19/class/CRP/6590',
	'167-CRP 6591 - Special Topics: Commercial Development in Real Estate-https://classes.cornell.edu/browse/roster/SP17/class/CRP/6591',
	'168-CRP 6592 - Special Topics: Retail Development in Real Estate-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'169-CRP 6593 - Special Topics: Introduction to Green Real Estate-https://classes.cornell.edu/browse/roster/SP17/class/CRP/6593',
	'170-CRP 6594 - Real Estate Competitions: UT Austin-https://classes.cornell.edu/browse/roster/SP19/class/CRP/6594',
	'171-CRP 6596 - Real Estate Competitions I: ULI Hines-https://classes.cornell.edu/browse/roster/WI19/class/CRP/6596',
	'172-CRP 6597 - Real Estate Competitions II: ULI Hines-https://classes.cornell.edu/browse/roster/SP19/class/CRP/6597',
	'173-CRP 6601 - Museum and the Public-https://classes.cornell.edu/browse/roster/SP18/class/CRP/6601',
	'174-CRP 6602 - Planning History: The American Case-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'175-CRP 6610 - Seminar in American Urban History-https://classes.cornell.edu/browse/roster/SP18/class/CRP/6610',
	'176-CRP 6630 - Historic Preservation Law-https://classes.cornell.edu/browse/roster/FA17/class/CRP/6630',
	'177-CRP 6640 - Economics and Financing of Neighborhood Conservation and Preservation-https://classes.cornell.edu/browse/roster/FA18/class/CRP/6640',
	'178-CRP 6650 - Preservation Planning and Urban Change-https://classes.cornell.edu/browse/roster/SP19/class/CRP/6650',
	'179-CRP 6660 - Pre-Industrial Cities and Towns in North America-https://classes.cornell.edu/browse/roster/SP18/class/CRP/6660',
	'180-CRP 6690 - Special Topics in History and Preservation-https://classes.cornell.edu/browse/roster/SP19/class/CRP/6690',
	'181-CRP 6700 - Regional Planning and Development in Developing Nations-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'182-CRP 6710 - Seminar in International Planning-https://classes.cornell.edu/browse/roster/FA14/class/CRP/6710',
	'183-CRP 6711 - Italy and the European Union-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'184-CRP 6720 - International Institutions-https://classes.cornell.edu/browse/roster/SP19/class/CRP/6720',
	'185-CRP 6740 - Urban Transformations in the Global South-https://classes.cornell.edu/browse/roster/FA15/class/CRP/6740',
	'186-CRP 6760 - Latino/a Latin American Cities-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'187-CRP 6770 - Seminar on Issues in African Development-https://classes.cornell.edu/browse/roster/SP19/class/CRP/6770',
	'188-CRP 6790 - Special Topics: Planning and Developing Regions-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'189-CRP 6791 - Special Topic-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'190-CRP 6792 - Planning and Poverty in the Global South-https://classes.cornell.edu/browse/roster/SP18/class/CRP/6792',
	'191-CRP 6801 - The Asian American Urban Experience: Past, Present, and Future-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'192-CRP 6860 - Planning for Sustainable Transportation-https://classes.cornell.edu/browse/roster/SP19/class/CRP/6860',
	'193-CRP 6890 - Special Topics in Environmental Planning-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'194-CRP 6900 - Graduate Seminar in Rome-https://classes.cornell.edu/browse/roster/SP19/class/CRP/6900',
	'195-CRP 6901 - Real Estate Review-https://classes.cornell.edu/browse/roster/SP19/class/CRP/6901',
	'196-CRP 6940 - Planning Internship in Rome-https://classes.cornell.edu/browse/roster/SP19/class/CRP/6940',
	'197-CRP 7190 - Special Topics in Planning Theory and Politics-https://classes.cornell.edu/browse/roster/FA14/class/CRP/7190',
	'198-CRP 7201 - Research Design-https://classes.cornell.edu/browse/roster/SP19/class/CRP/7201',
	'199-CRP 7770 - Theories of Development and Underdevelopment-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'200-CRP 7850 - City and Regional Futures: Planning Practice, Policy and Design-https://classes.cornell.edu/browse/roster/SP19/class/CRP/7850',
	'201-CRP 7940 - Planning Internship-https://classes.cornell.edu/browse/roster/SP19/class/CRP/7940',
	'202-CRP 7960 - Professional Writing and Publishing (Colloqui)-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'203-CRP 7970 - Independent Study for Graduate Students-https://classes.cornell.edu/browse/roster/SP19/class/CRP/7970',
	'204-CRP 8000 - Advanced Seminar in Urban & Regional Theory I-file:///C:/Users/25393/Desktop/test/cityPlanning/cornell/course.html',
	'205-CRP 8010 - Advanced Seminar in Urban and Regional Theory II-https://classes.cornell.edu/browse/roster/SP18/class/CRP/8010',
	'206-CRP 8100 - Seminar in Advanced Planning Theory-https://classes.cornell.edu/browse/roster/FA17/class/CRP/8100',
	'207-CRP 8300 - Seminar in Regional Science, Planning, and Policy Analysis-https://classes.cornell.edu/browse/roster/FA18/class/CRP/8300',
	'208-CRP 8900 - Planning Research Seminar-https://classes.cornell.edu/browse/roster/SP19/class/CRP/8900',
	'209-CRP 8901 - M.R.P. Exit Project: Research Paper-Research-https://classes.cornell.edu/browse/roster/SP19/class/CRP/8901',
	'210-CRP 8902 - M.R.P. Exit Project: Research Paper-Writing-https://classes.cornell.edu/browse/roster/SP19/class/CRP/8902',
	'211-CRP 8903 - M.R.P. Exit Project: Professional Report-Research-https://classes.cornell.edu/browse/roster/SP19/class/CRP/8903',
	'212-CRP 8904 - M.R.P. Exit Project: Professional Report-Writing-https://classes.cornell.edu/browse/roster/SP19/class/CRP/8904',
	'213-CRP 8905 - M.R.P. Exit Project: Thesis-Research-https://classes.cornell.edu/browse/roster/SP19/class/CRP/8905',
	'214-CRP 8906 - M.R.P. Exit Project: Thesis-Writing-https://classes.cornell.edu/browse/roster/SP19/class/CRP/8906',
	'215-CRP 8910 - Masters Thesis in Regional Science-https://classes.cornell.edu/browse/roster/SP19/class/CRP/8910',
	'216-CRP 8920 - Masters Thesis, Project, or Research Paper-https://classes.cornell.edu/browse/roster/SP17/class/CRP/8920',
	'217-CRP 8950 - Masters Thesis in Historic Preservation Planning-https://classes.cornell.edu/browse/roster/SP19/class/CRP/8950',
	'218-CRP 9920 - Doctoral Dissertation-https://classes.cornell.edu/browse/roster/SP19/class/CRP/9920',
];