let data=[
	'1-ARCH 1101 - Design I-https://classes.cornell.edu/browse/roster/FA18/class/ARCH/1101',
	'2-ARCH1102-Design II-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/1102',
	'3-ARCH 1103 - Elective Design Studio-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'4-ARCH 1104 - Elective Design Studio-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'5-ARCH 1110 - Introduction to Architecture: Design Studio-https://classes.cornell.edu/browse/roster/SU18/class/ARCH/1110',
	'6-ARCH 1120 - Architecture Design Studio-https://classes.cornell.edu/browse/roster/FA18/class/ARCH/1120',
	'7-ARCH 1300 - An Introduction to Architecture: Lectures-https://classes.cornell.edu/browse/roster/SU18/class/ARCH/1300',
	'8-ARCH1301-Introduction to Architecture-https://classes.cornell.edu/browse/roster/SP18/class/ARCH/1301',
	'9-ARCH 1501 - Representation I: Freehand Architectural Drawing-https://classes.cornell.edu/browse/roster/FA18/class/ARCH/1501',
	'10-ARCH1502-Representation II: Media of Representation-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/1502',
	'11-ARCH 1611 - Environmental Systems I: Site and Sustainability-https://classes.cornell.edu/browse/roster/FA18/class/ARCH/1611',
	'12-ARCH1612-Structural Concepts-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/1612',
	'13-ARCH 1801 - History of Architecture I-https://classes.cornell.edu/browse/roster/FA18/class/ARCH/1801',
	'14-ARCH1802-History of Architecture II-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/1802',
	'15-ARCH1901-FWS: Theme Parking: Using the History of the Theme Park to Understand Contemporary Built Environs-https://classes.cornell.edu/browse/roster/SP16/class/ARCH/1901',
	'16-ARCH 2100 - Elective Design Studio-https://classes.cornell.edu/browse/roster/SU18/class/ARCH/2100',
	'17-ARCH2101-Design III-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/2101',
	'18-ARCH2102-Design IV-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/2102',
	'19-ARCH 2301 - Architectural Analysis I: Buildings, Drawings, and Texts-https://classes.cornell.edu/browse/roster/FA18/class/ARCH/2301',
	'20-ARCH 2302 - Architectural Analysis II-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'21-ARCH 2503 - Drawing III: Digital Media in Architecture-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'22-ARCH 2601 - Environmental Systems I - Site Planning-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'23-ARCH 2602 - Building Technology, Materials, and Methods-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'24-ARCH 2603 - Structural Concepts-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'25-ARCH 2604 - Structural Elements-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'26-ARCH 2613 - Structural Systems-https://classes.cornell.edu/browse/roster/FA18/class/ARCH/2613',
	'27-ARCH 2614 - Building Technology I: Materials and Methods-https://classes.cornell.edu/browse/roster/FA18/class/ARCH/2614',
	'28-ARCH2615-Building Technology II: Structural Elements-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/2615',
	'29-ARCH2616-Environmental Systems II: Building Dynamics-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/2616',
	'30-ARCH2809-Undergraduate Independent Study in the History of Architecture and Urbanism-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/2809',
	'31-ARCH 3100 - Elective Design Studio-https://classes.cornell.edu/browse/roster/SU18/class/ARCH/3100',
	'32-ARCH3101-Design V-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/3101',
	'33-ARCH3102-Design VI-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/3102',
	'34-ARCH3103-Special Problems in Architectural Design-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/3103',
	'35-ARCH 3106 - Praxis: Community Design Workshop-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'36-ARCH 3109 - Elective Design Studio-https://classes.cornell.edu/browse/roster/SU18/class/ARCH/3109',
	'37-ARCH 3113 - Furniture Design (Technology)-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'38-ARCH3117-Contemporary Italian Culture - Italian Cinema-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/3117',
	'39-ARCH3301-Architectural Analysis II: Architecture, the City, and Landscape-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/3301',
	'40-ARCH3304-Column, Wall, Elevation, Facade: A Study of the Vertical Surface in Architecture-https://classes.cornell.edu/browse/roster/SP17/class/ARCH/3304',
	'41-ARCH3307-Special Investigations in the Theory of Architecture I-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/3307',
	'42-ARCH3308-Special Topics in the Theory of Architecture I-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/3308',
	'43-ARCH3309-Elements, Principles, and Theories in Japanese Architecture-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/3309',
	'44-ARCH 3310 - Modern Landscape Architecture-https://classes.cornell.edu/browse/roster/FA15/class/ARCH/3310',
	'45-ARCH 3311 - Tales of Two Cities-https://classes.cornell.edu/browse/roster/FA14/class/ARCH/3311',
	'46-ARCH 3402 - Architecture as a Cultural System-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'47-ARCH3409-Undergraduate Investigations in Architecture, Culture, and Society-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/3409',
	'48-ARCH 3420 - Architectural Field Studies-https://classes.cornell.edu/browse/roster/FA18/class/ARCH/3420',
	'49-ARCH 3520 - Architectural Portfolio Development-https://classes.cornell.edu/browse/roster/FA18/class/ARCH/3520',
	'50-ARCH 3601 - Environmental Systems II: Thermal Environmental Systems-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'51-ARCH 3602 - Environmental Systems III: Building Systems Integration-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'52-ARCH 3603 - Structural Systems-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'53-ARCH 3605 - Bridge Design-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'54-ARCH 3702 - Visual Imaging in the Electronic Age-https://classes.cornell.edu/browse/roster/FA17/class/ARCH/3702',
	'55-ARCH 3704 - Introduction to Computer Graphics-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'56-ARCH 3800 - History of Theory-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'57-ARCH 3806 - The Architecture of India and Its Interpretation-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'58-ARCH 3808 - Modernism-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'59-ARCH 3810 - American Architecture and Building I-https://classes.cornell.edu/browse/roster/FA18/class/ARCH/3810',
	'60-ARCH 3811 - American Architecture and Building II-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'61-ARCH 3812 - Edge Cities: Celluloid New York and Los Angeles-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'62-ARCH 3813 - The Cumulative City-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'63-ARCH 3815 - History of the Present- Contemporary Architecture and Urbanism-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'64-ARCH 3817 - Special Topics in the History of Architecture and Urbanism-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'65-ARCH3819-Special Topics in the History of Architecture and Urbanism-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/3819',
	'66-ARCH3820-The Topography and Urban History of Rome in Antiquity and the Middle Ages-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/3820',
	'67-ARCH 3821 - History of European Landscape Architecture-https://classes.cornell.edu/browse/roster/FA18/class/ARCH/3821',
	'68-ARCH3822-History of American Landscape Architecture-https://classes.cornell.edu/browse/roster/SP16/class/ARCH/3822',
	'69-ARCH3823-Urban Design, Architecture, and Art in Renaissance and Baroque Rome-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/3823',
	'70-ARCH 4100 - Elective Design Studio-https://classes.cornell.edu/browse/roster/SU18/class/ARCH/4100',
	'71-ARCH4101-Design VII-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/4101',
	'72-ARCH4102-Design VIII-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/4102',
	'73-ARCH4300-Architectural Publications-https://classes.cornell.edu/browse/roster/SP18/class/ARCH/4300',
	'74-ARCH 4308 - Sensation & Indigenous Intent-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'75-ARCH4408-Special Topics in Architecture, Culture, and Society-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/4408',
	'76-ARCH4409-Elements, Principles, and Theories in Japanese Architecture-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/4409',
	'77-ARCH 4418 - Special Topics in Architecture, Culture and Society-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'78-ARCH4500-Architectural Publications-https://classes.cornell.edu/browse/roster/SP18/class/ARCH/4500',
	'79-ARCH4508-Special Investigations in Visual Representation-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/4508',
	'80-ARCH4509-Special Topics in Visual Representation I-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/4509',
	'81-ARCH4513-Furniture Design-https://classes.cornell.edu/browse/roster/SP16/class/ARCH/4513',
	'82-ARCH 4601 - Ecological Literacy and Design-https://classes.cornell.edu/browse/roster/FA16/class/ARCH/4601',
	'83-ARCH4603-Special Topics in Structures-https://classes.cornell.edu/browse/roster/SP16/class/ARCH/4603',
	'84-ARCH4604-Special Investigations in Construction-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/4604',
	'85-ARCH4605-Special Topics in Construction-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/4605',
	'86-ARCH4609-Special Investigations in Structures-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/4609',
	'87-ARCH4613-Furniture Design-https://classes.cornell.edu/browse/roster/SP16/class/ARCH/4613',
	'88-ARCH4618-Special Investigations in Environmental Systems and Conservation-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/4618',
	'89-ARCH4619-Special Topics in Environmental Systems and Conservation-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/4619',
	'90-ARCH4621-Sustainable Architecture: The Science and Politics of Green Building-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/4621',
	'91-ARCH 4706 - Special Topics in Computer Applications-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'92-ARCH 4707 - Special Projects in Computer Graphics-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'93-ARCH 4708 - Special Projects in Computer Graphics-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'94-ARCH4901-Undergraduate Thesis in the History of Architecture and Urbanism-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/4901',
	'95-ARCH 5100 - Elective Design Studio-https://classes.cornell.edu/browse/roster/SU18/class/ARCH/5100',
	'96-ARCH5101-Design IX-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/5101',
	'97-ARCH 5103 - Design IXa-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'98-ARCH 5104 - Design Xa-https://classes.cornell.edu/browse/roster/SU18/class/ARCH/5104',
	'99-ARCH 5110 - Thesis Proseminar-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'100-ARCH 5111 - Core Design Studio I-https://classes.cornell.edu/browse/roster/FA18/class/ARCH/5111',
	'101-ARCH5112-Core Design Studio II-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/5112',
	'102-ARCH 5113 - Core Design Studio III-https://classes.cornell.edu/browse/roster/FA16/class/ARCH/5113',
	'103-ARCH5114-Core Design Studios IV: Integrative Design Practices-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/5114',
	'104-ARCH 5115 - Core Design Studios V: Expanded Practices-https://classes.cornell.edu/browse/roster/FA18/class/ARCH/5115',
	'105-ARCH5116-Vertical Design Studio-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/5116',
	'106-ARCH5201-Professional Practice-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/5201',
	'107-ARCH 5202 - Professional Seminar-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'108-ARCH5203-Multicultural Work Environments-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/5203',
	'109-ARCH5204-Professional Training-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/5204',
	'110-ARCH 5301 - Theories and Analyses of Architecture I-https://classes.cornell.edu/browse/roster/FA18/class/ARCH/5301',
	'111-ARCH5302-Theories and Analyses of Architecture II-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/5302',
	'112-ARCH5402-Architecture, Culture, and Society-https://classes.cornell.edu/browse/roster/SP15/class/ARCH/5402',
	'113-ARCH 5511 - Constructed Drawing I-https://classes.cornell.edu/browse/roster/FA18/class/ARCH/5511',
	'114-ARCH5512-Constructed Drawing II-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/5512',
	'115-ARCH 5602 - Building Technology, Materials, and Methods-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'116-ARCH 5603 - Structural Concepts-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'117-ARCH 5604 - Structural Elements-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'118-ARCH 5611 - Environmental Systems I: Site and Sustainability-https://classes.cornell.edu/browse/roster/FA18/class/ARCH/5611',
	'119-ARCH5612-Structural Concepts-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/5612',
	'120-ARCH 5613 - Structural Systems-https://classes.cornell.edu/browse/roster/FA18/class/ARCH/5613',
	'121-ARCH 5614 - Building Technology I: Materials and Methods-https://classes.cornell.edu/browse/roster/FA18/class/ARCH/5614',
	'122-ARCH5615-Building Technology II: Construction Elements-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/5615',
	'123-ARCH5616-Environmental Systems II: Building Dynamics-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/5616',
	'124-ARCH 5621 - Sustainable Architecture: The Science and Politics of Green Building-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'125-ARCH 5801 - History of Architecture I-https://classes.cornell.edu/browse/roster/FA18/class/ARCH/5801',
	'126-ARCH5802-History of Architecture II-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/5802',
	'127-ARCH 5810 - American Architecture and Building I-https://classes.cornell.edu/browse/roster/FA18/class/ARCH/5810',
	'128-ARCH5819-Special Topics in the History of Architecture and Urbanism-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/5819',
	'129-ARCH 5821 - History of European Landscape Architecture-https://classes.cornell.edu/browse/roster/FA18/class/ARCH/5821',
	'130-ARCH5822-History of American Landscape Architecture-https://classes.cornell.edu/browse/roster/SP16/class/ARCH/5822',
	'131-ARCH5902-Design X Thesis-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/5902',
	'132-ARCH5903-Design IX Expanded Design Thesis-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/5903',
	'133-ARCH 6106 - Praxis: Community Design Workshop-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'134-ARCH 6109 - Special Problems in Design-https://classes.cornell.edu/browse/roster/FA18/class/ARCH/6109',
	'135-ARCH 6110 - Computational Thinking as Design Process-https://classes.cornell.edu/browse/roster/SU18/class/ARCH/6110',
	'136-ARCH 6301 - Architectural Territories of Design-https://classes.cornell.edu/browse/roster/SU18/class/ARCH/6301',
	'137-ARCH6304-Column, Wall, Elevation, Facade: A Study of the Vertical Surface in Architecture-https://classes.cornell.edu/browse/roster/SP17/class/ARCH/6304',
	'138-ARCH6307-Special Investigations in the Theory of Architecture II-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/6307',
	'139-ARCH6308-Special Topics in the Theory of Architecture II-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/6308',
	'140-ARCH6309-Elements, Principles, and Theories in Japanese Architecture-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/6309',
	'141-ARCH 6310 - Modern Landscape Architecture-https://classes.cornell.edu/browse/roster/FA15/class/ARCH/6310',
	'142-ARCH 6311 - Tales of Two Cities-https://classes.cornell.edu/browse/roster/FA14/class/ARCH/6311',
	'143-ARCH6408-Special Topics in Architecture, Culture, and Society-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/6408',
	'144-ARCH6409-Graduate Investigations in Architecture, Culture, and Society-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/6409',
	'145-ARCH6508-Special Investigations in Visual Representation II-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/6508',
	'146-ARCH6509-Special Topics in Visual Representation II-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/6509',
	'147-ARCH 6601 - Environmental Systems II: Thermal Environmental Systems-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'148-ARCH 6602 - Environmental Systems III - Building Systems Integration-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'149-ARCH 6603 - Structural Systems-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'150-ARCH6605-Special Topics in Construction-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/6605',
	'151-ARCH6609-Special Investigations in Structures-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/6609',
	'152-ARCH 6800 - State of the Discipline-https://classes.cornell.edu/browse/roster/FA18/class/ARCH/6800',
	'153-ARCH 6801 - Foundations of the Discipline-https://classes.cornell.edu/browse/roster/FA17/class/ARCH/6801',
	'154-ARCH 6803 - Seminar in History of Theory-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'155-ARCH6805-Practicum-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/6805',
	'156-ARCH 6806 - Seminar in Seventeenth and Eighteenth-Century Architecture and Urbanism-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'157-ARCH 6808 - Seminar in 20th-Century Architecture and Urbanism-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'158-ARCH 6816 - Seminar in Special Topics in the History of Architecture and Urbanism-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'159-ARCH6819-Seminar in Special Topics in the History of Architecture and Urbanism-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/6819',
	'160-ARCH7101-Problems in Architecture Design-https://classes.cornell.edu/browse/roster/SP17/class/ARCH/7101',
	'161-ARCH 7111 - Design A-https://classes.cornell.edu/browse/roster/SU18/class/ARCH/7111',
	'162-ARCH7112-Design B: Topic Studio-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/7112',
	'163-ARCH7113-Design C: Topic Studio-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/7113',
	'164-ARCH 7151 - Design Topic Research Studio: Matter Design Computation-https://classes.cornell.edu/browse/roster/FA18/class/ARCH/7151',
	'165-ARCH7152-Design Topic Research Studio 2: Matter Design Computation-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/7152',
	'166-ARCH 7701 - Architectural Science Laboratory-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'167-ARCH7702-Architectural Science Laboratory-https://classes.cornell.edu/browse/roster/SP17/class/ARCH/7702',
	'168-ARCH7809-Graduate Independent Study in the History of Architecture and Urbanism-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/7809',
	'169-ARCH7903-Thesis or Research in Architectural Science-https://classes.cornell.edu/browse/roster/SP17/class/ARCH/7903',
	'170-ARCH7904-Thesis or Research in Architectural Science-https://classes.cornell.edu/browse/roster/SP17/class/ARCH/7904',
	'171-ARCH7912-Design B: Topics Studio-https://classes.cornell.edu/browse/roster/SP18/class/ARCH/7912',
	'172-ARCH8104-Design VIIa-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/8104',
	'173-ARCH 8901 - Thesis or Research in Architectural Design-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'174-ARCH 8902 - Thesis or Research in Urban Design-file:///C:/Users/25393/Desktop/test/major/architechture/cornell/course.html',
	'175-ARCH8903-Projects in Advanced Architectural Design-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/8903',
	'176-ARCH8904-Independent Design Thesis-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/8904',
	'177-ARCH8906-Thesis in Advanced Architectural Design I-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/8906',
	'178-ARCH8911-Proseminar in Design Research-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/8911',
	'179-ARCH8912-Independent Design Thesis-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/8912',
	'180-ARCH8913-Design C: Topic Studio-https://classes.cornell.edu/browse/roster/SP18/class/ARCH/8913',
	'181-ARCH 8920 - M.A. Essay Research-https://classes.cornell.edu/browse/roster/FA18/class/ARCH/8920',
	'182-ARCH 8921 - M.A. Essay in the History of Architecture and Urbanism-https://classes.cornell.edu/browse/roster/FA18/class/ARCH/8921',
	'183-ARCH9901-Ph.D. Dissertation in the History of Architecture and Urbanism-https://classes.cornell.edu/browse/roster/SP19/class/ARCH/9901',
];